{{- if .Values.objectStorage.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.objectStorage.credentialsSecretName }}
  labels:
    {{- include "shoal.labels" . | nindent 4 }}
type: Opaque
stringData:
  key.json: |
{{ .Values.objectStorage.gcsKeyJson | indent 4 }}
  accumulo-password: {{ .Values.readFleet.accumuloPassword | quote }}
{{- end }}
