// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: embed.proto

package embedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Splits        []string               `protobuf:"bytes,2,rep,name=splits,proto3" json:"splits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTableRequest) Reset() {
	*x = CreateTableRequest{}
	mi := &file_embed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTableRequest) ProtoMessage() {}

func (x *CreateTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTableRequest.ProtoReflect.Descriptor instead.
func (*CreateTableRequest) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTableRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *CreateTableRequest) GetSplits() []string {
	if x != nil {
		return x.Splits
	}
	return nil
}

type CreateTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Tablets       int32                  `protobuf:"varint,2,opt,name=tablets,proto3" json:"tablets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTableResponse) Reset() {
	*x = CreateTableResponse{}
	mi := &file_embed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTableResponse) ProtoMessage() {}

func (x *CreateTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTableResponse.ProtoReflect.Descriptor instead.
func (*CreateTableResponse) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTableResponse) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *CreateTableResponse) GetTablets() int32 {
	if x != nil {
		return x.Tablets
	}
	return 0
}

type Mutation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           []byte                 `protobuf:"bytes,1,opt,name=row,proto3" json:"row,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_embed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{2}
}

func (x *Mutation) GetRow() []byte {
	if x != nil {
		return x.Row
	}
	return nil
}

func (x *Mutation) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Entry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ColumnFamily     []byte                 `protobuf:"bytes,1,opt,name=column_family,json=columnFamily,proto3" json:"column_family,omitempty"`
	ColumnQualifier  []byte                 `protobuf:"bytes,2,opt,name=column_qualifier,json=columnQualifier,proto3" json:"column_qualifier,omitempty"`
	ColumnVisibility []byte                 `protobuf:"bytes,3,opt,name=column_visibility,json=columnVisibility,proto3" json:"column_visibility,omitempty"`
	Timestamp        int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value            []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Delete           bool                   `protobuf:"varint,6,opt,name=delete,proto3" json:"delete,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_embed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{3}
}

func (x *Entry) GetColumnFamily() []byte {
	if x != nil {
		return x.ColumnFamily
	}
	return nil
}

func (x *Entry) GetColumnQualifier() []byte {
	if x != nil {
		return x.ColumnQualifier
	}
	return nil
}

func (x *Entry) GetColumnVisibility() []byte {
	if x != nil {
		return x.ColumnVisibility
	}
	return nil
}

func (x *Entry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Entry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Entry) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Mutations     []*Mutation            `protobuf:"bytes,2,rep,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_embed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{4}
}

func (x *WriteRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *WriteRequest) GetMutations() []*Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Written       int32                  `protobuf:"varint,1,opt,name=written,proto3" json:"written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_embed_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{5}
}

func (x *WriteResponse) GetWritten() int32 {
	if x != nil {
		return x.Written
	}
	return 0
}

type ScanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Table string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	// Row prefix for prefix scans (mutually exclusive with start/end).
	RowPrefix string `protobuf:"bytes,2,opt,name=row_prefix,json=rowPrefix,proto3" json:"row_prefix,omitempty"`
	// Explicit range bounds.
	StartRow       []byte `protobuf:"bytes,3,opt,name=start_row,json=startRow,proto3" json:"start_row,omitempty"`
	StartInclusive bool   `protobuf:"varint,4,opt,name=start_inclusive,json=startInclusive,proto3" json:"start_inclusive,omitempty"`
	EndRow         []byte `protobuf:"bytes,5,opt,name=end_row,json=endRow,proto3" json:"end_row,omitempty"`
	EndInclusive   bool   `protobuf:"varint,6,opt,name=end_inclusive,json=endInclusive,proto3" json:"end_inclusive,omitempty"`
	// Max cells to return (0 = unlimited).
	Limit int32 `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	// Batch size for streaming chunks (0 = server default).
	BatchSize int32 `protobuf:"varint,8,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	// Optional server-side term-index (keyword) pushdown. When set, the scan
	// resolves the given posting rows to their referenced primary rows and
	// streams back the primary rows' cells instead of the raw range. This is
	// additive: a request that leaves term_filter unset behaves exactly as
	// before.
	TermFilter *TermFilter `protobuf:"bytes,9,opt,name=term_filter,json=termFilter,proto3" json:"term_filter,omitempty"`
	// Optional server-side vector k-NN pushdown. When set, the scan scores
	// packed-float32 embedding cells in range against a query vector and streams
	// back only the top-k cells, each cell's value replaced by a big-endian
	// float32 similarity score (score-descending). This is additive: a request
	// that leaves vector_search unset behaves exactly as before. term_filter and
	// vector_search are mutually exclusive.
	VectorSearch *VectorSearch `protobuf:"bytes,10,opt,name=vector_search,json=vectorSearch,proto3" json:"vector_search,omitempty"`
	// Optional server-side one-hop graph expansion. When set, the scan walks the
	// given anchor rows' edge cells, resolves the embedded neighbor ids to
	// neighbor rows, and streams back those rows' cells. This is additive: a
	// request that leaves edge_expand unset behaves exactly as before. At most
	// one of term_filter, vector_search, edge_expand and score_filter may be set.
	EdgeExpand *EdgeExpand `protobuf:"bytes,11,opt,name=edge_expand,json=edgeExpand,proto3" json:"edge_expand,omitempty"`
	// Optional server-side read-time scoring pushdown. When set, the scan scores
	// cells in range, keeps the top-k, and streams those cells with the value
	// replaced by a big-endian float32 score (score-descending). This is
	// additive: a request that leaves score_filter unset behaves exactly as
	// before. At most one of term_filter, vector_search, edge_expand and
	// score_filter may be set.
	ScoreFilter *ScoreFilter `protobuf:"bytes,12,opt,name=score_filter,json=scoreFilter,proto3" json:"score_filter,omitempty"`
	// Optional as-of (time-travel) ceiling: when > 0, the scan ignores every
	// cell whose timestamp is greater than as_of, reconstructing the table as
	// it existed at that instant. Applied beneath versioning/deletion so the
	// newest surviving version <= as_of wins and tombstones written after as_of
	// are not yet in effect — matching Accumulo's timestamp-filter semantics.
	// Additive: as_of <= 0 (the default) behaves exactly as before. Works with
	// plain range/prefix scans; it is independent of the pushdown filters above.
	AsOf          int64 `protobuf:"varint,13,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_embed_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{6}
}

func (x *ScanRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ScanRequest) GetRowPrefix() string {
	if x != nil {
		return x.RowPrefix
	}
	return ""
}

func (x *ScanRequest) GetStartRow() []byte {
	if x != nil {
		return x.StartRow
	}
	return nil
}

func (x *ScanRequest) GetStartInclusive() bool {
	if x != nil {
		return x.StartInclusive
	}
	return false
}

func (x *ScanRequest) GetEndRow() []byte {
	if x != nil {
		return x.EndRow
	}
	return nil
}

func (x *ScanRequest) GetEndInclusive() bool {
	if x != nil {
		return x.EndInclusive
	}
	return false
}

func (x *ScanRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ScanRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *ScanRequest) GetTermFilter() *TermFilter {
	if x != nil {
		return x.TermFilter
	}
	return nil
}

func (x *ScanRequest) GetVectorSearch() *VectorSearch {
	if x != nil {
		return x.VectorSearch
	}
	return nil
}

func (x *ScanRequest) GetEdgeExpand() *EdgeExpand {
	if x != nil {
		return x.EdgeExpand
	}
	return nil
}

func (x *ScanRequest) GetScoreFilter() *ScoreFilter {
	if x != nil {
		return x.ScoreFilter
	}
	return nil
}

func (x *ScanRequest) GetAsOf() int64 {
	if x != nil {
		return x.AsOf
	}
	return 0
}

// TermFilter configures the term-index pushdown iterator. A consumer
// maintains an inverted index as ordinary cells — posting rows (e.g.
// "idx:<term>") with one cell per matching primary row. TermFilter moves the
// "scan postings, then point-lookup each primary row" join server-side: the
// engine walks the listed posting rows, resolves each posting to a primary
// row, and returns the primary rows' cells directly.
//
// The engine defines only the mechanism (resolve postings -> primary rows);
// the posting/primary schema is the consumer's, supplied here per scan.
type TermFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Posting row keys to look up, e.g. "idx:graph". Postings from all rows are
	// unioned and de-duplicated before resolution.
	TermRows [][]byte `protobuf:"bytes,1,rep,name=term_rows,json=termRows,proto3" json:"term_rows,omitempty"`
	// Prefix prepended to each resolved id to form the primary row key. Empty
	// means the resolved id is itself the full primary row.
	PrimaryPrefix []byte `protobuf:"bytes,2,opt,name=primary_prefix,json=primaryPrefix,proto3" json:"primary_prefix,omitempty"`
	// Where in a posting cell the primary id lives: "qualifier" (default) reads
	// the column qualifier; "value" reads the cell value.
	IdSource string `protobuf:"bytes,3,opt,name=id_source,json=idSource,proto3" json:"id_source,omitempty"`
	// Optional column family restriction: when non-empty, only posting cells
	// with this column family are treated as postings. Empty = every cell in a
	// posting row is a posting.
	PostingCf []byte `protobuf:"bytes,4,opt,name=posting_cf,json=postingCf,proto3" json:"posting_cf,omitempty"`
	// When true, postings from term_rows are matched as an ordered adjacent
	// phrase instead of the existing union/de-duplicate keyword behavior. Unset
	// false preserves the original TermFilter semantics exactly.
	Phrase bool `protobuf:"varint,5,opt,name=phrase,proto3" json:"phrase,omitempty"`
	// Optional numeric-valued posting range. When set, only postings whose
	// consumer-encoded numeric value falls within the requested bounds are
	// resolved. Unset preserves the original TermFilter semantics exactly.
	NumericRange  *NumericRange `protobuf:"bytes,6,opt,name=numeric_range,json=numericRange,proto3" json:"numeric_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermFilter) Reset() {
	*x = TermFilter{}
	mi := &file_embed_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermFilter) ProtoMessage() {}

func (x *TermFilter) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermFilter.ProtoReflect.Descriptor instead.
func (*TermFilter) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{7}
}

func (x *TermFilter) GetTermRows() [][]byte {
	if x != nil {
		return x.TermRows
	}
	return nil
}

func (x *TermFilter) GetPrimaryPrefix() []byte {
	if x != nil {
		return x.PrimaryPrefix
	}
	return nil
}

func (x *TermFilter) GetIdSource() string {
	if x != nil {
		return x.IdSource
	}
	return ""
}

func (x *TermFilter) GetPostingCf() []byte {
	if x != nil {
		return x.PostingCf
	}
	return nil
}

func (x *TermFilter) GetPhrase() bool {
	if x != nil {
		return x.Phrase
	}
	return false
}

func (x *TermFilter) GetNumericRange() *NumericRange {
	if x != nil {
		return x.NumericRange
	}
	return nil
}

// NumericRange restricts term postings whose consumer-owned numeric value is
// within lower/upper bounds. The engine defines only the range mechanism; the
// posting value schema and numeric meaning are supplied by the consumer.
type NumericRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Lower bound value. Used only when lower_set is true.
	Lower    float64 `protobuf:"fixed64,1,opt,name=lower,proto3" json:"lower,omitempty"`
	LowerSet bool    `protobuf:"varint,2,opt,name=lower_set,json=lowerSet,proto3" json:"lower_set,omitempty"`
	// Upper bound value. Used only when upper_set is true.
	Upper    float64 `protobuf:"fixed64,3,opt,name=upper,proto3" json:"upper,omitempty"`
	UpperSet bool    `protobuf:"varint,4,opt,name=upper_set,json=upperSet,proto3" json:"upper_set,omitempty"`
	// Bound inclusivity. Defaults false mean exclusive when the bound is set.
	LowerInclusive bool `protobuf:"varint,5,opt,name=lower_inclusive,json=lowerInclusive,proto3" json:"lower_inclusive,omitempty"`
	UpperInclusive bool `protobuf:"varint,6,opt,name=upper_inclusive,json=upperInclusive,proto3" json:"upper_inclusive,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NumericRange) Reset() {
	*x = NumericRange{}
	mi := &file_embed_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericRange) ProtoMessage() {}

func (x *NumericRange) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericRange.ProtoReflect.Descriptor instead.
func (*NumericRange) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{8}
}

func (x *NumericRange) GetLower() float64 {
	if x != nil {
		return x.Lower
	}
	return 0
}

func (x *NumericRange) GetLowerSet() bool {
	if x != nil {
		return x.LowerSet
	}
	return false
}

func (x *NumericRange) GetUpper() float64 {
	if x != nil {
		return x.Upper
	}
	return 0
}

func (x *NumericRange) GetUpperSet() bool {
	if x != nil {
		return x.UpperSet
	}
	return false
}

func (x *NumericRange) GetLowerInclusive() bool {
	if x != nil {
		return x.LowerInclusive
	}
	return false
}

func (x *NumericRange) GetUpperInclusive() bool {
	if x != nil {
		return x.UpperInclusive
	}
	return false
}

// VectorSearch configures the brute-force vector k-NN pushdown iterator. A
// consumer co-locates an embedding with its primary row as an ordinary cell —
// a reserved column family whose value is the embedding packed as big-endian
// float32. VectorSearch moves the "stream every embedding back and rank it"
// search server-side: the engine scores each embedding cell against the query,
// keeps the k best, and returns those cells with the value replaced by a
// big-endian float32 similarity score, best first.
//
// The engine defines only the mechanism (score cells -> top-k); the embedding
// schema is the consumer's, supplied here per scan.
type VectorSearch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query vector, packed big-endian float32 (length = dim*4). Required.
	Query []byte `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Number of nearest cells to return (k). 0 = server default (10).
	TopK int32 `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	// Optional column family restriction: when non-empty, only cells with this
	// column family are treated as embeddings. Empty = every cell in range.
	EmbeddingCf []byte `protobuf:"bytes,3,opt,name=embedding_cf,json=embeddingCf,proto3" json:"embedding_cf,omitempty"`
	// Similarity metric: "cosine" (default when empty), "dot", or "l2".
	Metric string `protobuf:"bytes,4,opt,name=metric,proto3" json:"metric,omitempty"`
	// Optional lower bound: cells scoring below it are dropped. Scores are
	// oriented so larger is better (l2 uses negative squared distance), so this
	// filters the same way for every metric. Unset (0) means no minimum is
	// applied unless min_score_set is true.
	MinScore float32 `protobuf:"fixed32,5,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	// Distinguishes "min_score deliberately 0" from "min_score unset".
	MinScoreSet   bool `protobuf:"varint,6,opt,name=min_score_set,json=minScoreSet,proto3" json:"min_score_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorSearch) Reset() {
	*x = VectorSearch{}
	mi := &file_embed_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearch) ProtoMessage() {}

func (x *VectorSearch) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearch.ProtoReflect.Descriptor instead.
func (*VectorSearch) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{9}
}

func (x *VectorSearch) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *VectorSearch) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *VectorSearch) GetEmbeddingCf() []byte {
	if x != nil {
		return x.EmbeddingCf
	}
	return nil
}

func (x *VectorSearch) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *VectorSearch) GetMinScore() float32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *VectorSearch) GetMinScoreSet() bool {
	if x != nil {
		return x.MinScoreSet
	}
	return false
}

// ScoreFilter configures the read-time scoring pushdown iterator. A consumer
// stores score inputs as ordinary cells: vectors, timestamps, or feature
// values in a reserved column family. ScoreFilter moves the "stream cells,
// compute a consumer-selected score, then keep top-k" step server-side: the
// engine scores each candidate cell, keeps the k best, and returns those cells
// with the value replaced by a big-endian float32 score, best first.
//
// The engine defines only the mechanism (score cells -> top-k); the scoring
// schema and method parameters are the consumer's, supplied here per scan.
type ScoreFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional column family restriction for the value to score. Empty = every
	// cell in range is a candidate.
	ScoreCf []byte `protobuf:"bytes,1,opt,name=score_cf,json=scoreCf,proto3" json:"score_cf,omitempty"`
	// Scoring selector, e.g. "vector_sim", "time_decay", or "linear". Empty =
	// server default for the requested deployment.
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Optional query vector, packed big-endian float32. Methods that need a query
	// vector (for example vector_sim) require this to be non-empty.
	Query []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	// Number of scored cells to return (k). 0 = server default (10).
	TopK int32 `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	// Method-specific float parameters, interpreted by the consumer-selected
	// method (for example feature weights or decay coefficients).
	Params []float32 `protobuf:"fixed32,5,rep,packed,name=params,proto3" json:"params,omitempty"`
	// Timestamp anchor for time-decay scoring, in Unix milliseconds. 0 means the
	// server may use its default anchor (typically now).
	TimestampAnchorMs int64 `protobuf:"varint,6,opt,name=timestamp_anchor_ms,json=timestampAnchorMs,proto3" json:"timestamp_anchor_ms,omitempty"`
	// Half-life for time-decay scoring, in milliseconds. 0 means no explicit
	// half-life was supplied.
	HalfLifeMs    int64 `protobuf:"varint,7,opt,name=half_life_ms,json=halfLifeMs,proto3" json:"half_life_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreFilter) Reset() {
	*x = ScoreFilter{}
	mi := &file_embed_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreFilter) ProtoMessage() {}

func (x *ScoreFilter) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreFilter.ProtoReflect.Descriptor instead.
func (*ScoreFilter) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{10}
}

func (x *ScoreFilter) GetScoreCf() []byte {
	if x != nil {
		return x.ScoreCf
	}
	return nil
}

func (x *ScoreFilter) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ScoreFilter) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ScoreFilter) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *ScoreFilter) GetParams() []float32 {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ScoreFilter) GetTimestampAnchorMs() int64 {
	if x != nil {
		return x.TimestampAnchorMs
	}
	return 0
}

func (x *ScoreFilter) GetHalfLifeMs() int64 {
	if x != nil {
		return x.HalfLifeMs
	}
	return 0
}

// EdgeExpand configures the one-hop graph-expansion pushdown iterator. A
// consumer co-locates a node's out-edges with the node row as ordinary cells —
// each edge is a cell whose column family marks it as an edge and whose column
// qualifier (or value) encodes the relationship and the neighbor's id.
// EdgeExpand moves the "scan edges, then point-lookup each neighbor" traversal
// server-side: the engine walks the listed anchor rows' edge cells, extracts
// each neighbor id, resolves it to a neighbor row, and returns the neighbor
// rows' cells directly.
//
// The engine defines only the mechanism (anchor edge cells -> neighbor rows);
// the edge schema is the consumer's, supplied here per scan — no relationship
// or column-family vocabulary is baked in.
type EdgeExpand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Anchor (source) row keys to expand from. Neighbors from all anchors are
	// unioned and de-duplicated.
	AnchorRows [][]byte `protobuf:"bytes,1,rep,name=anchor_rows,json=anchorRows,proto3" json:"anchor_rows,omitempty"`
	// Optional column family marking edge cells on an anchor row. Empty = every
	// cell on an anchor row is an edge.
	EdgeCf []byte `protobuf:"bytes,2,opt,name=edge_cf,json=edgeCf,proto3" json:"edge_cf,omitempty"`
	// Where the edge token (the relationship+neighbor encoding) lives in an edge
	// cell: "qualifier" (default) reads the column qualifier; "value" reads the
	// cell value.
	EdgeField string `protobuf:"bytes,3,opt,name=edge_field,json=edgeField,proto3" json:"edge_field,omitempty"`
	// Optional separator splitting the edge token into fields (e.g. a NUL between
	// relationship and neighbor id). Empty = the whole token is the neighbor id.
	FieldSep []byte `protobuf:"bytes,4,opt,name=field_sep,json=fieldSep,proto3" json:"field_sep,omitempty"`
	// When field_sep is set, the split-field index holding the neighbor id; -1
	// (the default when id_index_set is false) = the last field.
	IdIndex int32 `protobuf:"varint,5,opt,name=id_index,json=idIndex,proto3" json:"id_index,omitempty"`
	// Distinguishes "id_index deliberately 0" from "id_index unset (-1)".
	IdIndexSet bool `protobuf:"varint,6,opt,name=id_index_set,json=idIndexSet,proto3" json:"id_index_set,omitempty"`
	// When field_sep is set, the split-field index holding the relationship
	// (default 0); used only for relationship filtering.
	RelIndex int32 `protobuf:"varint,7,opt,name=rel_index,json=relIndex,proto3" json:"rel_index,omitempty"`
	// Optional relationship allowlist: when non-empty, only edges whose
	// relationship field is listed are expanded. Requires field_sep.
	Relationships []string `protobuf:"bytes,8,rep,name=relationships,proto3" json:"relationships,omitempty"`
	// Prepended to each neighbor id to form the neighbor row key.
	PrimaryPrefix []byte `protobuf:"bytes,9,opt,name=primary_prefix,json=primaryPrefix,proto3" json:"primary_prefix,omitempty"`
	// When true, also emit the anchor rows' own cells.
	IncludeAnchors bool `protobuf:"varint,10,opt,name=include_anchors,json=includeAnchors,proto3" json:"include_anchors,omitempty"`
	// Optional hop limit for intent-biased traversal. Unset/0 preserves today's
	// exact one-hop expansion semantics; values > 1 request multi-hop expansion.
	MaxHops int32 `protobuf:"varint,11,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`
	// Optional relationship weights for intent-bias. Weights bias
	// which edge types are followed during multi-hop expansion; an empty list
	// preserves the existing unweighted relationship allowlist behavior.
	EdgeWeights   []*EdgeWeight `protobuf:"bytes,12,rep,name=edge_weights,json=edgeWeights,proto3" json:"edge_weights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeExpand) Reset() {
	*x = EdgeExpand{}
	mi := &file_embed_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeExpand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeExpand) ProtoMessage() {}

func (x *EdgeExpand) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeExpand.ProtoReflect.Descriptor instead.
func (*EdgeExpand) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{11}
}

func (x *EdgeExpand) GetAnchorRows() [][]byte {
	if x != nil {
		return x.AnchorRows
	}
	return nil
}

func (x *EdgeExpand) GetEdgeCf() []byte {
	if x != nil {
		return x.EdgeCf
	}
	return nil
}

func (x *EdgeExpand) GetEdgeField() string {
	if x != nil {
		return x.EdgeField
	}
	return ""
}

func (x *EdgeExpand) GetFieldSep() []byte {
	if x != nil {
		return x.FieldSep
	}
	return nil
}

func (x *EdgeExpand) GetIdIndex() int32 {
	if x != nil {
		return x.IdIndex
	}
	return 0
}

func (x *EdgeExpand) GetIdIndexSet() bool {
	if x != nil {
		return x.IdIndexSet
	}
	return false
}

func (x *EdgeExpand) GetRelIndex() int32 {
	if x != nil {
		return x.RelIndex
	}
	return 0
}

func (x *EdgeExpand) GetRelationships() []string {
	if x != nil {
		return x.Relationships
	}
	return nil
}

func (x *EdgeExpand) GetPrimaryPrefix() []byte {
	if x != nil {
		return x.PrimaryPrefix
	}
	return nil
}

func (x *EdgeExpand) GetIncludeAnchors() bool {
	if x != nil {
		return x.IncludeAnchors
	}
	return false
}

func (x *EdgeExpand) GetMaxHops() int32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

func (x *EdgeExpand) GetEdgeWeights() []*EdgeWeight {
	if x != nil {
		return x.EdgeWeights
	}
	return nil
}

// EdgeWeight assigns an intent weight to one relationship type during multi-hop
// graph expansion. Relationship strings use the consumer's edge vocabulary.
type EdgeWeight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relationship  string                 `protobuf:"bytes,1,opt,name=relationship,proto3" json:"relationship,omitempty"`
	Weight        float32                `protobuf:"fixed32,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeWeight) Reset() {
	*x = EdgeWeight{}
	mi := &file_embed_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeWeight) ProtoMessage() {}

func (x *EdgeWeight) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeWeight.ProtoReflect.Descriptor instead.
func (*EdgeWeight) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{12}
}

func (x *EdgeWeight) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

func (x *EdgeWeight) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type Cell struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Row              []byte                 `protobuf:"bytes,1,opt,name=row,proto3" json:"row,omitempty"`
	ColumnFamily     []byte                 `protobuf:"bytes,2,opt,name=column_family,json=columnFamily,proto3" json:"column_family,omitempty"`
	ColumnQualifier  []byte                 `protobuf:"bytes,3,opt,name=column_qualifier,json=columnQualifier,proto3" json:"column_qualifier,omitempty"`
	ColumnVisibility []byte                 `protobuf:"bytes,4,opt,name=column_visibility,json=columnVisibility,proto3" json:"column_visibility,omitempty"`
	Timestamp        int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value            []byte                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_embed_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{13}
}

func (x *Cell) GetRow() []byte {
	if x != nil {
		return x.Row
	}
	return nil
}

func (x *Cell) GetColumnFamily() []byte {
	if x != nil {
		return x.ColumnFamily
	}
	return nil
}

func (x *Cell) GetColumnQualifier() []byte {
	if x != nil {
		return x.ColumnQualifier
	}
	return nil
}

func (x *Cell) GetColumnVisibility() []byte {
	if x != nil {
		return x.ColumnVisibility
	}
	return nil
}

func (x *Cell) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Cell) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*Cell                `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_embed_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{14}
}

func (x *ScanResponse) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type FlushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRequest) Reset() {
	*x = FlushRequest{}
	mi := &file_embed_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRequest) ProtoMessage() {}

func (x *FlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRequest.ProtoReflect.Descriptor instead.
func (*FlushRequest) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{15}
}

func (x *FlushRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type FlushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushResponse) Reset() {
	*x = FlushResponse{}
	mi := &file_embed_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushResponse) ProtoMessage() {}

func (x *FlushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushResponse.ProtoReflect.Descriptor instead.
func (*FlushResponse) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{16}
}

type CompactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactRequest) Reset() {
	*x = CompactRequest{}
	mi := &file_embed_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactRequest) ProtoMessage() {}

func (x *CompactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactRequest.ProtoReflect.Descriptor instead.
func (*CompactRequest) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{17}
}

func (x *CompactRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type CompactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactResponse) Reset() {
	*x = CompactResponse{}
	mi := &file_embed_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactResponse) ProtoMessage() {}

func (x *CompactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactResponse.ProtoReflect.Descriptor instead.
func (*CompactResponse) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{18}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_embed_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{19}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []string               `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_embed_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{20}
}

func (x *StatusResponse) GetTables() []string {
	if x != nil {
		return x.Tables
	}
	return nil
}

var File_embed_proto protoreflect.FileDescriptor

const file_embed_proto_rawDesc = "" +
	"\n" +
	"\vembed.proto\x12\x0eshoal.embed.v1\"B\n" +
	"\x12CreateTableRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x16\n" +
	"\x06splits\x18\x02 \x03(\tR\x06splits\"E\n" +
	"\x13CreateTableResponse\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x18\n" +
	"\atablets\x18\x02 \x01(\x05R\atablets\"M\n" +
	"\bMutation\x12\x10\n" +
	"\x03row\x18\x01 \x01(\fR\x03row\x12/\n" +
	"\aentries\x18\x02 \x03(\v2\x15.shoal.embed.v1.EntryR\aentries\"\xd0\x01\n" +
	"\x05Entry\x12#\n" +
	"\rcolumn_family\x18\x01 \x01(\fR\fcolumnFamily\x12)\n" +
	"\x10column_qualifier\x18\x02 \x01(\fR\x0fcolumnQualifier\x12+\n" +
	"\x11column_visibility\x18\x03 \x01(\fR\x10columnVisibility\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x12\x16\n" +
	"\x06delete\x18\x06 \x01(\bR\x06delete\"\\\n" +
	"\fWriteRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x126\n" +
	"\tmutations\x18\x02 \x03(\v2\x18.shoal.embed.v1.MutationR\tmutations\")\n" +
	"\rWriteResponse\x12\x18\n" +
	"\awritten\x18\x01 \x01(\x05R\awritten\"\x8d\x04\n" +
	"\vScanRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x1d\n" +
	"\n" +
	"row_prefix\x18\x02 \x01(\tR\trowPrefix\x12\x1b\n" +
	"\tstart_row\x18\x03 \x01(\fR\bstartRow\x12'\n" +
	"\x0fstart_inclusive\x18\x04 \x01(\bR\x0estartInclusive\x12\x17\n" +
	"\aend_row\x18\x05 \x01(\fR\x06endRow\x12#\n" +
	"\rend_inclusive\x18\x06 \x01(\bR\fendInclusive\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"batch_size\x18\b \x01(\x05R\tbatchSize\x12;\n" +
	"\vterm_filter\x18\t \x01(\v2\x1a.shoal.embed.v1.TermFilterR\n" +
	"termFilter\x12A\n" +
	"\rvector_search\x18\n" +
	" \x01(\v2\x1c.shoal.embed.v1.VectorSearchR\fvectorSearch\x12;\n" +
	"\vedge_expand\x18\v \x01(\v2\x1a.shoal.embed.v1.EdgeExpandR\n" +
	"edgeExpand\x12>\n" +
	"\fscore_filter\x18\f \x01(\v2\x1b.shoal.embed.v1.ScoreFilterR\vscoreFilter\x12\x13\n" +
	"\x05as_of\x18\r \x01(\x03R\x04asOf\"\xe7\x01\n" +
	"\n" +
	"TermFilter\x12\x1b\n" +
	"\tterm_rows\x18\x01 \x03(\fR\btermRows\x12%\n" +
	"\x0eprimary_prefix\x18\x02 \x01(\fR\rprimaryPrefix\x12\x1b\n" +
	"\tid_source\x18\x03 \x01(\tR\bidSource\x12\x1d\n" +
	"\n" +
	"posting_cf\x18\x04 \x01(\fR\tpostingCf\x12\x16\n" +
	"\x06phrase\x18\x05 \x01(\bR\x06phrase\x12A\n" +
	"\rnumeric_range\x18\x06 \x01(\v2\x1c.shoal.embed.v1.NumericRangeR\fnumericRange\"\xc6\x01\n" +
	"\fNumericRange\x12\x14\n" +
	"\x05lower\x18\x01 \x01(\x01R\x05lower\x12\x1b\n" +
	"\tlower_set\x18\x02 \x01(\bR\blowerSet\x12\x14\n" +
	"\x05upper\x18\x03 \x01(\x01R\x05upper\x12\x1b\n" +
	"\tupper_set\x18\x04 \x01(\bR\bupperSet\x12'\n" +
	"\x0flower_inclusive\x18\x05 \x01(\bR\x0elowerInclusive\x12'\n" +
	"\x0fupper_inclusive\x18\x06 \x01(\bR\x0eupperInclusive\"\xb5\x01\n" +
	"\fVectorSearch\x12\x14\n" +
	"\x05query\x18\x01 \x01(\fR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12!\n" +
	"\fembedding_cf\x18\x03 \x01(\fR\vembeddingCf\x12\x16\n" +
	"\x06metric\x18\x04 \x01(\tR\x06metric\x12\x1b\n" +
	"\tmin_score\x18\x05 \x01(\x02R\bminScore\x12\"\n" +
	"\rmin_score_set\x18\x06 \x01(\bR\vminScoreSet\"\xd5\x01\n" +
	"\vScoreFilter\x12\x19\n" +
	"\bscore_cf\x18\x01 \x01(\fR\ascoreCf\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x14\n" +
	"\x05query\x18\x03 \x01(\fR\x05query\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\x05R\x04topK\x12\x16\n" +
	"\x06params\x18\x05 \x03(\x02R\x06params\x12.\n" +
	"\x13timestamp_anchor_ms\x18\x06 \x01(\x03R\x11timestampAnchorMs\x12 \n" +
	"\fhalf_life_ms\x18\a \x01(\x03R\n" +
	"halfLifeMs\"\xac\x03\n" +
	"\n" +
	"EdgeExpand\x12\x1f\n" +
	"\vanchor_rows\x18\x01 \x03(\fR\n" +
	"anchorRows\x12\x17\n" +
	"\aedge_cf\x18\x02 \x01(\fR\x06edgeCf\x12\x1d\n" +
	"\n" +
	"edge_field\x18\x03 \x01(\tR\tedgeField\x12\x1b\n" +
	"\tfield_sep\x18\x04 \x01(\fR\bfieldSep\x12\x19\n" +
	"\bid_index\x18\x05 \x01(\x05R\aidIndex\x12 \n" +
	"\fid_index_set\x18\x06 \x01(\bR\n" +
	"idIndexSet\x12\x1b\n" +
	"\trel_index\x18\a \x01(\x05R\brelIndex\x12$\n" +
	"\rrelationships\x18\b \x03(\tR\rrelationships\x12%\n" +
	"\x0eprimary_prefix\x18\t \x01(\fR\rprimaryPrefix\x12'\n" +
	"\x0finclude_anchors\x18\n" +
	" \x01(\bR\x0eincludeAnchors\x12\x19\n" +
	"\bmax_hops\x18\v \x01(\x05R\amaxHops\x12=\n" +
	"\fedge_weights\x18\f \x03(\v2\x1a.shoal.embed.v1.EdgeWeightR\vedgeWeights\"H\n" +
	"\n" +
	"EdgeWeight\x12\"\n" +
	"\frelationship\x18\x01 \x01(\tR\frelationship\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x02R\x06weight\"\xc9\x01\n" +
	"\x04Cell\x12\x10\n" +
	"\x03row\x18\x01 \x01(\fR\x03row\x12#\n" +
	"\rcolumn_family\x18\x02 \x01(\fR\fcolumnFamily\x12)\n" +
	"\x10column_qualifier\x18\x03 \x01(\fR\x0fcolumnQualifier\x12+\n" +
	"\x11column_visibility\x18\x04 \x01(\fR\x10columnVisibility\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x06 \x01(\fR\x05value\":\n" +
	"\fScanResponse\x12*\n" +
	"\x05cells\x18\x01 \x03(\v2\x14.shoal.embed.v1.CellR\x05cells\"$\n" +
	"\fFlushRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\"\x0f\n" +
	"\rFlushResponse\"&\n" +
	"\x0eCompactRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\"\x11\n" +
	"\x0fCompactResponse\"\x0f\n" +
	"\rStatusRequest\"(\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06tables\x18\x01 \x03(\tR\x06tables2\xca\x03\n" +
	"\n" +
	"ShoalEmbed\x12V\n" +
	"\vCreateTable\x12\".shoal.embed.v1.CreateTableRequest\x1a#.shoal.embed.v1.CreateTableResponse\x12D\n" +
	"\x05Write\x12\x1c.shoal.embed.v1.WriteRequest\x1a\x1d.shoal.embed.v1.WriteResponse\x12C\n" +
	"\x04Scan\x12\x1b.shoal.embed.v1.ScanRequest\x1a\x1c.shoal.embed.v1.ScanResponse0\x01\x12D\n" +
	"\x05Flush\x12\x1c.shoal.embed.v1.FlushRequest\x1a\x1d.shoal.embed.v1.FlushResponse\x12J\n" +
	"\aCompact\x12\x1e.shoal.embed.v1.CompactRequest\x1a\x1f.shoal.embed.v1.CompactResponse\x12G\n" +
	"\x06Status\x12\x1d.shoal.embed.v1.StatusRequest\x1a\x1e.shoal.embed.v1.StatusResponseB,Z*github.com/phrocker/shoal/internal/embedpbb\x06proto3"

var (
	file_embed_proto_rawDescOnce sync.Once
	file_embed_proto_rawDescData []byte
)

func file_embed_proto_rawDescGZIP() []byte {
	file_embed_proto_rawDescOnce.Do(func() {
		file_embed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_embed_proto_rawDesc), len(file_embed_proto_rawDesc)))
	})
	return file_embed_proto_rawDescData
}

var file_embed_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_embed_proto_goTypes = []any{
	(*CreateTableRequest)(nil),  // 0: shoal.embed.v1.CreateTableRequest
	(*CreateTableResponse)(nil), // 1: shoal.embed.v1.CreateTableResponse
	(*Mutation)(nil),            // 2: shoal.embed.v1.Mutation
	(*Entry)(nil),               // 3: shoal.embed.v1.Entry
	(*WriteRequest)(nil),        // 4: shoal.embed.v1.WriteRequest
	(*WriteResponse)(nil),       // 5: shoal.embed.v1.WriteResponse
	(*ScanRequest)(nil),         // 6: shoal.embed.v1.ScanRequest
	(*TermFilter)(nil),          // 7: shoal.embed.v1.TermFilter
	(*NumericRange)(nil),        // 8: shoal.embed.v1.NumericRange
	(*VectorSearch)(nil),        // 9: shoal.embed.v1.VectorSearch
	(*ScoreFilter)(nil),         // 10: shoal.embed.v1.ScoreFilter
	(*EdgeExpand)(nil),          // 11: shoal.embed.v1.EdgeExpand
	(*EdgeWeight)(nil),          // 12: shoal.embed.v1.EdgeWeight
	(*Cell)(nil),                // 13: shoal.embed.v1.Cell
	(*ScanResponse)(nil),        // 14: shoal.embed.v1.ScanResponse
	(*FlushRequest)(nil),        // 15: shoal.embed.v1.FlushRequest
	(*FlushResponse)(nil),       // 16: shoal.embed.v1.FlushResponse
	(*CompactRequest)(nil),      // 17: shoal.embed.v1.CompactRequest
	(*CompactResponse)(nil),     // 18: shoal.embed.v1.CompactResponse
	(*StatusRequest)(nil),       // 19: shoal.embed.v1.StatusRequest
	(*StatusResponse)(nil),      // 20: shoal.embed.v1.StatusResponse
}
var file_embed_proto_depIdxs = []int32{
	3,  // 0: shoal.embed.v1.Mutation.entries:type_name -> shoal.embed.v1.Entry
	2,  // 1: shoal.embed.v1.WriteRequest.mutations:type_name -> shoal.embed.v1.Mutation
	7,  // 2: shoal.embed.v1.ScanRequest.term_filter:type_name -> shoal.embed.v1.TermFilter
	9,  // 3: shoal.embed.v1.ScanRequest.vector_search:type_name -> shoal.embed.v1.VectorSearch
	11, // 4: shoal.embed.v1.ScanRequest.edge_expand:type_name -> shoal.embed.v1.EdgeExpand
	10, // 5: shoal.embed.v1.ScanRequest.score_filter:type_name -> shoal.embed.v1.ScoreFilter
	8,  // 6: shoal.embed.v1.TermFilter.numeric_range:type_name -> shoal.embed.v1.NumericRange
	12, // 7: shoal.embed.v1.EdgeExpand.edge_weights:type_name -> shoal.embed.v1.EdgeWeight
	13, // 8: shoal.embed.v1.ScanResponse.cells:type_name -> shoal.embed.v1.Cell
	0,  // 9: shoal.embed.v1.ShoalEmbed.CreateTable:input_type -> shoal.embed.v1.CreateTableRequest
	4,  // 10: shoal.embed.v1.ShoalEmbed.Write:input_type -> shoal.embed.v1.WriteRequest
	6,  // 11: shoal.embed.v1.ShoalEmbed.Scan:input_type -> shoal.embed.v1.ScanRequest
	15, // 12: shoal.embed.v1.ShoalEmbed.Flush:input_type -> shoal.embed.v1.FlushRequest
	17, // 13: shoal.embed.v1.ShoalEmbed.Compact:input_type -> shoal.embed.v1.CompactRequest
	19, // 14: shoal.embed.v1.ShoalEmbed.Status:input_type -> shoal.embed.v1.StatusRequest
	1,  // 15: shoal.embed.v1.ShoalEmbed.CreateTable:output_type -> shoal.embed.v1.CreateTableResponse
	5,  // 16: shoal.embed.v1.ShoalEmbed.Write:output_type -> shoal.embed.v1.WriteResponse
	14, // 17: shoal.embed.v1.ShoalEmbed.Scan:output_type -> shoal.embed.v1.ScanResponse
	16, // 18: shoal.embed.v1.ShoalEmbed.Flush:output_type -> shoal.embed.v1.FlushResponse
	18, // 19: shoal.embed.v1.ShoalEmbed.Compact:output_type -> shoal.embed.v1.CompactResponse
	20, // 20: shoal.embed.v1.ShoalEmbed.Status:output_type -> shoal.embed.v1.StatusResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_embed_proto_init() }
func file_embed_proto_init() {
	if File_embed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_embed_proto_rawDesc), len(file_embed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_embed_proto_goTypes,
		DependencyIndexes: file_embed_proto_depIdxs,
		MessageInfos:      file_embed_proto_msgTypes,
	}.Build()
	File_embed_proto = out.File
	file_embed_proto_goTypes = nil
	file_embed_proto_depIdxs = nil
}
