// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: embed.proto

package embedpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShoalEmbed_CreateTable_FullMethodName = "/shoal.embed.v1.ShoalEmbed/CreateTable"
	ShoalEmbed_Write_FullMethodName       = "/shoal.embed.v1.ShoalEmbed/Write"
	ShoalEmbed_Scan_FullMethodName        = "/shoal.embed.v1.ShoalEmbed/Scan"
	ShoalEmbed_Flush_FullMethodName       = "/shoal.embed.v1.ShoalEmbed/Flush"
	ShoalEmbed_Compact_FullMethodName     = "/shoal.embed.v1.ShoalEmbed/Compact"
	ShoalEmbed_Status_FullMethodName      = "/shoal.embed.v1.ShoalEmbed/Status"
)

// ShoalEmbedClient is the client API for ShoalEmbed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ShoalEmbed is the gRPC service for the embedded storage engine.
// It exposes table management, writes, scans, compaction, and status.
type ShoalEmbedClient interface {
	// CreateTable creates a new table with optional split points.
	CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error)
	// Write writes a batch of mutations to a table.
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	// Scan reads cells from a table. Results are streamed back.
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanResponse], error)
	// Flush forces memtables to RFiles for a table.
	Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error)
	// Compact runs major compaction on a table.
	Compact(ctx context.Context, in *CompactRequest, opts ...grpc.CallOption) (*CompactResponse, error)
	// Status returns engine metadata (table list, etc.).
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type shoalEmbedClient struct {
	cc grpc.ClientConnInterface
}

func NewShoalEmbedClient(cc grpc.ClientConnInterface) ShoalEmbedClient {
	return &shoalEmbedClient{cc}
}

func (c *shoalEmbedClient) CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTableResponse)
	err := c.cc.Invoke(ctx, ShoalEmbed_CreateTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoalEmbedClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, ShoalEmbed_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoalEmbedClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShoalEmbed_ServiceDesc.Streams[0], ShoalEmbed_Scan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanRequest, ScanResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShoalEmbed_ScanClient = grpc.ServerStreamingClient[ScanResponse]

func (c *shoalEmbedClient) Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushResponse)
	err := c.cc.Invoke(ctx, ShoalEmbed_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoalEmbedClient) Compact(ctx context.Context, in *CompactRequest, opts ...grpc.CallOption) (*CompactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompactResponse)
	err := c.cc.Invoke(ctx, ShoalEmbed_Compact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoalEmbedClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ShoalEmbed_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShoalEmbedServer is the server API for ShoalEmbed service.
// All implementations must embed UnimplementedShoalEmbedServer
// for forward compatibility.
//
// ShoalEmbed is the gRPC service for the embedded storage engine.
// It exposes table management, writes, scans, compaction, and status.
type ShoalEmbedServer interface {
	// CreateTable creates a new table with optional split points.
	CreateTable(context.Context, *CreateTableRequest) (*CreateTableResponse, error)
	// Write writes a batch of mutations to a table.
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	// Scan reads cells from a table. Results are streamed back.
	Scan(*ScanRequest, grpc.ServerStreamingServer[ScanResponse]) error
	// Flush forces memtables to RFiles for a table.
	Flush(context.Context, *FlushRequest) (*FlushResponse, error)
	// Compact runs major compaction on a table.
	Compact(context.Context, *CompactRequest) (*CompactResponse, error)
	// Status returns engine metadata (table list, etc.).
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedShoalEmbedServer()
}

// UnimplementedShoalEmbedServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShoalEmbedServer struct{}

func (UnimplementedShoalEmbedServer) CreateTable(context.Context, *CreateTableRequest) (*CreateTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTable not implemented")
}
func (UnimplementedShoalEmbedServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedShoalEmbedServer) Scan(*ScanRequest, grpc.ServerStreamingServer[ScanResponse]) error {
	return status.Error(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedShoalEmbedServer) Flush(context.Context, *FlushRequest) (*FlushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedShoalEmbedServer) Compact(context.Context, *CompactRequest) (*CompactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Compact not implemented")
}
func (UnimplementedShoalEmbedServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedShoalEmbedServer) mustEmbedUnimplementedShoalEmbedServer() {}
func (UnimplementedShoalEmbedServer) testEmbeddedByValue()                    {}

// UnsafeShoalEmbedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShoalEmbedServer will
// result in compilation errors.
type UnsafeShoalEmbedServer interface {
	mustEmbedUnimplementedShoalEmbedServer()
}

func RegisterShoalEmbedServer(s grpc.ServiceRegistrar, srv ShoalEmbedServer) {
	// If the following call panics, it indicates UnimplementedShoalEmbedServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShoalEmbed_ServiceDesc, srv)
}

func _ShoalEmbed_CreateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoalEmbedServer).CreateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoalEmbed_CreateTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoalEmbedServer).CreateTable(ctx, req.(*CreateTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoalEmbed_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoalEmbedServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoalEmbed_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoalEmbedServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoalEmbed_Scan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShoalEmbedServer).Scan(m, &grpc.GenericServerStream[ScanRequest, ScanResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShoalEmbed_ScanServer = grpc.ServerStreamingServer[ScanResponse]

func _ShoalEmbed_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoalEmbedServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoalEmbed_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoalEmbedServer).Flush(ctx, req.(*FlushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoalEmbed_Compact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoalEmbedServer).Compact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoalEmbed_Compact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoalEmbedServer).Compact(ctx, req.(*CompactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoalEmbed_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoalEmbedServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoalEmbed_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoalEmbedServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShoalEmbed_ServiceDesc is the grpc.ServiceDesc for ShoalEmbed service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShoalEmbed_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shoal.embed.v1.ShoalEmbed",
	HandlerType: (*ShoalEmbedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTable",
			Handler:    _ShoalEmbed_CreateTable_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _ShoalEmbed_Write_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _ShoalEmbed_Flush_Handler,
		},
		{
			MethodName: "Compact",
			Handler:    _ShoalEmbed_Compact_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _ShoalEmbed_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Scan",
			Handler:       _ShoalEmbed_Scan_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "embed.proto",
}
