// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed with this
// work for additional information regarding copyright ownership.
package auth

import (
	"strings"
	"testing"

	"github.com/phrocker/shoal-oss/pkg/shoal"
)

// legacyFingerprintProbes are decisions that carry no executor binding,
// covering every combination of the two earlier optional sections (the
// ontology lens and grant provenance), a trusted-service decision, and a
// role-less decision granting execute, which is the shape fleet tests build.
func legacyFingerprintProbes(t *testing.T) map[string]DecisionConfig {
	t.Helper()
	withProvenance := func(config DecisionConfig) DecisionConfig {
		config.GrantProvenance = approverProvenance()
		return config
	}
	service := func(config DecisionConfig) DecisionConfig {
		config.AllowedOperations = []Operation{OperationInvoke}
		config.ServiceRole = ServiceRoleActionInvocation
		config.ServiceCeilingIdentity = "ceiling-invoke"
		return config
	}
	execute := func(config DecisionConfig) DecisionConfig {
		config.AllowedOperations = []Operation{OperationExecute}
		return config
	}
	return map[string]DecisionConfig{
		"plain":               provenanceTestConfig(t, false),
		"ontology":            provenanceTestConfig(t, true),
		"provenance":          withProvenance(provenanceTestConfig(t, false)),
		"ontology+provenance": withProvenance(provenanceTestConfig(t, true)),
		"service role":        service(provenanceTestConfig(t, false)),
		"service role+ontology+provenance": withProvenance(
			service(provenanceTestConfig(t, true))),
		"execute without role": execute(provenanceTestConfig(t, false)),
		"execute without role+ontology+provenance": withProvenance(
			execute(provenanceTestConfig(t, true))),
	}
}

// TestFingerprintWithoutExecutorBindingIsUnchanged pins decisions that carry
// no executor binding to fingerprints computed by the encoder on origin/main
// (3182ee16), before bindings existed. The literals were generated by that
// code and must never be recomputed: fingerprints are persisted on action and
// approval records and compared on replay.
func TestFingerprintWithoutExecutorBindingIsUnchanged(t *testing.T) {
	want := map[string]string{
		"plain":                            "auth-sha256:89e9dd693e464a66e704ced9da5e77adb90125c15bc9980378c3cb4dea90e51e",
		"ontology":                         "auth-sha256:cf9c569f7043fbb154015c83e8615282acacb0cbcb97b015059376e8e10da05e",
		"provenance":                       "auth-sha256:7cf93eed8793e06784849f4e692468df82d4fddc4f307f8198c03adc14b4fd88",
		"ontology+provenance":              "auth-sha256:6020d1ed0e793abc86d1b14103cc1e758fa9367cd82a869d98c469e07e097592",
		"service role":                     "auth-sha256:58d648118410b9796c144feb4bbe2ee5f2d31b8a7d9018255112ea497f78ad1f",
		"service role+ontology+provenance": "auth-sha256:2dff08f4b524db62fa870a3ee205677a3413d713ea1bc81a1c56d6f63c7605fe",
		"execute without role":             "auth-sha256:f788c08513d6516c3e33189a7496a9f8b557e10ebf7104bb6781221fb0c298a8",
		"execute without role+ontology+provenance": "auth-sha256:68ae9728d61b03fee72b051b8d5470a7e17b2adea7fe97b12aad15bb97c479e4",
	}
	probes := legacyFingerprintProbes(t)
	if len(probes) != len(want) {
		t.Fatalf("probes = %d, pinned = %d", len(probes), len(want))
	}
	for name, config := range probes {
		decision, err := NewDecision(config)
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		if decision.ExecutorBinding() != "" {
			t.Fatalf("%s: unbound decision reports a binding", name)
		}
		fingerprint, err := AuthorizationFingerprint(decision)
		if err != nil {
			t.Fatal(err)
		}
		if fingerprint.String() != want[name] {
			t.Errorf("%s fingerprint = %s, want %s",
				name, fingerprint.String(), want[name])
		}
	}
}

func executorTestConfig(
	t *testing.T, withOntology bool, binding string,
) DecisionConfig {
	t.Helper()
	config := provenanceTestConfig(t, withOntology)
	config.AllowedOperations = []Operation{OperationExecute}
	config.ServiceRole = ServiceRoleActionExecution
	config.ServiceCeilingIdentity = "ceiling-execute"
	config.ExecutorBinding = binding
	return config
}

func mustFingerprint(t *testing.T, config DecisionConfig) Fingerprint {
	t.Helper()
	decision, err := NewDecision(config)
	if err != nil {
		t.Fatal(err)
	}
	fingerprint, err := AuthorizationFingerprint(decision)
	if err != nil {
		t.Fatal(err)
	}
	return fingerprint
}

// TestExecutorBindingIsFingerprinted: the binding narrows authority, so
// decisions differing only in their binding, or in whether they carry one,
// must never share a fingerprint, with or without the other optional
// sections.
func TestExecutorBindingIsFingerprinted(t *testing.T) {
	seen := map[Fingerprint]string{}
	record := func(name string, fingerprint Fingerprint) {
		t.Helper()
		if previous, ok := seen[fingerprint]; ok {
			t.Fatalf("%s collides with %s", name, previous)
		}
		seen[fingerprint] = name
	}
	for name, config := range legacyFingerprintProbes(t) {
		record(name, mustFingerprint(t, config))
	}
	for _, withOntology := range []bool{false, true} {
		for _, withProvenance := range []bool{false, true} {
			for _, binding := range []string{"executor-x", "executor-y"} {
				config := executorTestConfig(t, withOntology, binding)
				name := binding
				if withOntology {
					name += "+ontology"
				}
				if withProvenance {
					config.GrantProvenance = approverProvenance()
					name += "+provenance"
				}
				record(name, mustFingerprint(t, config))
			}
		}
	}

	// Binding versus no binding on otherwise identical material. The role
	// requires a binding, so the unbound twin is the decision the encoder
	// sees with the binding section dropped: the same fields, hashed as the
	// pre-binding encoder did.
	bound, err := NewDecision(executorTestConfig(t, false, "executor-x"))
	if err != nil {
		t.Fatal(err)
	}
	unbound := bound
	unbound.executorBinding = ""
	boundFingerprint, err := AuthorizationFingerprint(bound)
	if err != nil {
		t.Fatal(err)
	}
	// The helper must match the real encoder on a decision with no optional
	// section, or the comparison below would prove nothing.
	legacy, err := NewDecision(legacyFingerprintProbes(t)["service role"])
	if err != nil {
		t.Fatal(err)
	}
	if real, _ := AuthorizationFingerprint(legacy); real != unboundFingerprintForTest(legacy) {
		t.Fatal("unboundFingerprintForTest drifted from AuthorizationFingerprint")
	}
	// cloneValidated refuses the role without a binding, so hash directly.
	if boundFingerprint == unboundFingerprintForTest(unbound) {
		t.Fatal("a binding does not reach the fingerprint")
	}
}

// unboundFingerprintForTest hashes the decision's fields the way
// AuthorizationFingerprint does, without validating it, so the encoding of an
// action-execution decision with no binding can be compared.
func unboundFingerprintForTest(d Decision) Fingerprint {
	encoder := newDigestEncoder("explorer-authorization-fingerprint-v1")
	encoder.bytes(d.domain)
	encoder.int64(d.policyGeneration)
	encoder.text(string(d.subject))
	encoder.text(string(d.actor))
	encoder.text(string(d.clientID))
	encoder.uint64(uint64(len(d.onBehalfOf)))
	for _, identity := range d.onBehalfOf {
		encoder.text(string(identity))
	}
	encoder.uint64(uint64(len(d.operations)))
	for _, operation := range d.operations {
		encoder.text(string(operation))
	}
	encoder.uint64(uint64(len(d.sources)))
	for _, source := range d.sources {
		encoder.bytes(source)
	}
	encoder.uint64(uint64(len(d.policies)))
	for _, policy := range d.policies {
		encoder.bytes(policy)
	}
	encoder.text(string(d.serviceRole))
	encoder.text(string(d.serviceCeilingIdentity))
	return Fingerprint(encoder.sum())
}

// TestExecutorBindingFingerprintIsPinned pins a bound decision's encoding, so
// a change to its marker (for example one colliding with provenance's 2) or
// to where the section sits is caught even where no collision is observable.
func TestExecutorBindingFingerprintIsPinned(t *testing.T) {
	all := executorTestConfig(t, true, "executor-x")
	all.GrantProvenance = approverProvenance()
	for name, probe := range map[string]struct {
		config DecisionConfig
		want   string
	}{
		"bound": {executorTestConfig(t, false, "executor-x"),
			"auth-sha256:6e6c6611104d39b45bdd7539d017b06a7ea8110f7b6d6389b35eab1855a9f2c6"},
		"bound+ontology+provenance": {all,
			"auth-sha256:6d086af602980ef0ab4a2634e3dcc89c89e63938816759ef291ca21bed44b915"},
	} {
		if got := mustFingerprint(t, probe.config).String(); got != probe.want {
			t.Errorf("%s fingerprint = %s, want %s", name, got, probe.want)
		}
	}
}

func TestExecutorBindingValidation(t *testing.T) {
	invalid := map[string]func(*DecisionConfig){
		"role without binding": func(c *DecisionConfig) { c.ExecutorBinding = "" },
		"binding without role": func(c *DecisionConfig) {
			c.ServiceRole = ""
			c.ServiceCeilingIdentity = ""
		},
		"binding with another role": func(c *DecisionConfig) {
			c.ServiceRole = ServiceRoleActionInvocation
			c.AllowedOperations = []Operation{OperationInvoke}
		},
		"oversized": func(c *DecisionConfig) {
			c.ExecutorBinding = strings.Repeat("x", shoal.MaxIDBytes+1)
		},
		"control byte":       func(c *DecisionConfig) { c.ExecutorBinding = "executor\nx" },
		"surrounding spaces": func(c *DecisionConfig) { c.ExecutorBinding = " executor" },
		"invalid utf-8":      func(c *DecisionConfig) { c.ExecutorBinding = "executor\xff" },
		"on behalf of": func(c *DecisionConfig) {
			c.OnBehalfOf = []shoal.ID{"oidc:https://issuer.example#alice"}
		},
	}
	for name, edit := range invalid {
		config := executorTestConfig(t, false, "executor-x")
		edit(&config)
		if _, err := NewDecision(config); !shoal.IsErrorCode(
			err, shoal.ErrorInvalidArgument) {
			t.Errorf("%s: NewDecision() = %v, want invalid_argument", name, err)
		}
	}

	atBound := executorTestConfig(
		t, false, strings.Repeat("x", shoal.MaxIDBytes))
	if _, err := NewDecision(atBound); err != nil {
		t.Fatalf("binding at the bound: %v", err)
	}
	decision, err := NewDecision(executorTestConfig(t, false, "executor-x"))
	if err != nil {
		t.Fatal(err)
	}
	if decision.ExecutorBinding() != "executor-x" {
		t.Fatalf("binding = %q", decision.ExecutorBinding())
	}
	// A chain stays valid on every unbound decision, including role-less
	// execute; only the binding forbids it.
	delegated := provenanceTestConfig(t, false)
	delegated.AllowedOperations = []Operation{OperationExecute}
	delegated.OnBehalfOf = []shoal.ID{"oidc:https://issuer.example#alice"}
	if _, err := NewDecision(delegated); err != nil {
		t.Fatalf("unbound delegated decision: %v", err)
	}
}

// TestCloneValidatedCarriesExecutorBinding: every fingerprint and
// authorization check runs on cloneValidated's copy, so a dropped binding
// would make a bound decision fail its own role validation.
func TestCloneValidatedCarriesExecutorBinding(t *testing.T) {
	decision, err := NewDecision(executorTestConfig(t, false, "executor-x"))
	if err != nil {
		t.Fatal(err)
	}
	cloned, err := decision.cloneValidated()
	if err != nil {
		t.Fatal(err)
	}
	if cloned.ExecutorBinding() != "executor-x" {
		t.Fatalf("clone binding = %q", cloned.ExecutorBinding())
	}
	if err := decision.Authorize(OperationExecute, ResourceRequest{
		AuthorizationDomain: decision.AuthorizationDomain(),
	}, decision.AuthenticationExpires().Add(-1)); err != nil {
		t.Fatalf("bound decision cannot authorize execute: %v", err)
	}
}
