"""Incremental Shoal Python binding; intentionally not full compatibility."""

from ._version import __version__
from ._native import ForkSafetyError, NativeAPI, RuntimeInfo
from .admin import (
    NamespaceOperations,
    NamespacePermissions,
    SecurityOperations,
    ShoalSystemPermissions,
    ShoalTablePermissions,
    SystemPermissions,
    TableInfo,
    TableOperations,
    TablePermissions,
)
from .client import (
    AccumuloBase,
    AccumuloIterator,
    AccumuloScanner,
    AccumuloWriter,
    BatchScanner,
    Client,
    Connector,
    Scanner,
    Results,
)
from .data import Authorizations, Key, KeyValue, Range, Value
from .compatibility import IterInfo, LoggingConfiguration, PythonIterator, ScannerOptions
from .errors import (
    AmbiguousWriteError,
    AlreadyExistsError,
    CancelledError,
    ClientException,
    ClosedError,
    DeadlineExceededError,
    InvalidArgumentError,
    NotFoundError,
    PermissionDeniedError,
    ShoalError,
    UnsupportedError,
)
from .writer import BatchWriter, BatchWriterOptions, Mutation
from .storage import (
    Hdfs,
    HdfsDirEnt,
    HdfsInputStream,
    HdfsOutputStream,
    RFileOperations,
    SequentialRFile,
)

AccumuloConnector = Connector

__all__ = [
    "__version__",
    "AccumuloBase",
    "AccumuloConnector",
    "AccumuloIterator",
    "AccumuloScanner",
    "AccumuloWriter",
    "AmbiguousWriteError",
    "AlreadyExistsError",
    "Authorizations",
    "BatchWriter",
    "BatchWriterOptions",
    "BatchScanner",
    "CancelledError",
    "Client",
    "ClientException",
    "ClosedError",
    "Connector",
    "DeadlineExceededError",
    "InvalidArgumentError",
    "Hdfs",
    "HdfsDirEnt",
    "HdfsInputStream",
    "HdfsOutputStream",
    "ForkSafetyError",
    "Key",
    "KeyValue",
    "IterInfo",
    "Range",
    "LoggingConfiguration",
    "NativeAPI",
    "NamespaceOperations",
    "NamespacePermissions",
    "NotFoundError",
    "PermissionDeniedError",
    "RuntimeInfo",
    "RFileOperations",
    "PythonIterator",
    "Results",
    "Scanner",
    "ScannerOptions",
    "SecurityOperations",
    "ShoalSystemPermissions",
    "ShoalTablePermissions",
    "ShoalError",
    "UnsupportedError",
    "SystemPermissions",
    "TableInfo",
    "TableOperations",
    "TablePermissions",
    "Mutation",
    "Value",
    "SequentialRFile",
]
