"""Incremental Shoal Python binding; intentionally not full compatibility."""

from ._version import __version__
from ._native import NativeAPI, RuntimeInfo
from .admin import (
    Authorizations,
    NamespaceOperations,
    NamespacePermissions,
    SecurityOperations,
    ShoalSystemPermissions,
    ShoalTablePermissions,
    SystemPermissions,
    TableInfo,
    TableOperations,
    TablePermissions,
)
from .client import (
    AccumuloBase,
    AccumuloIterator,
    AccumuloScanner,
    AccumuloWriter,
    Client,
    Connector,
    Key,
    Scanner,
)
from .compatibility import LoggingConfiguration, PythonIterator, ScannerOptions
from .configuration import (
    AccumuloInfo,
    AuthInfo,
    Compacting,
    Configuration,
    DeadServer,
    Instance,
    RecoveryStatus,
    TableCompactions,
    TableRates,
    TabletServerStatus,
    ZookeeperInstance,
)
from .errors import (
    AmbiguousWriteError,
    AlreadyExistsError,
    CancelledError,
    ClientException,
    ClosedError,
    DeadlineExceededError,
    InvalidArgumentError,
    NotFoundError,
    PermissionDeniedError,
    ShoalError,
    UnsupportedError,
)
from .writer import BatchWriter, BatchWriterOptions, Mutation
from .storage import (
    Hdfs,
    HdfsDirEnt,
    HdfsInputStream,
    HdfsOutputStream,
    KeyValue,
    RFileOperations,
    SequentialRFile,
)

AccumuloConnector = Connector

__all__ = [
    "__version__",
    "AccumuloBase",
    "AccumuloConnector",
    "AccumuloIterator",
    "AccumuloInfo",
    "AccumuloScanner",
    "AccumuloWriter",
    "AmbiguousWriteError",
    "AlreadyExistsError",
    "Authorizations",
    "AuthInfo",
    "BatchWriter",
    "BatchWriterOptions",
    "CancelledError",
    "Client",
    "ClientException",
    "ClosedError",
    "Connector",
    "Configuration",
    "Compacting",
    "DeadlineExceededError",
    "DeadServer",
    "InvalidArgumentError",
    "Instance",
    "Hdfs",
    "HdfsDirEnt",
    "HdfsInputStream",
    "HdfsOutputStream",
    "Key",
    "KeyValue",
    "LoggingConfiguration",
    "NativeAPI",
    "NamespaceOperations",
    "NamespacePermissions",
    "NotFoundError",
    "PermissionDeniedError",
    "RuntimeInfo",
    "RFileOperations",
    "RecoveryStatus",
    "PythonIterator",
    "Scanner",
    "ScannerOptions",
    "SecurityOperations",
    "ShoalSystemPermissions",
    "ShoalTablePermissions",
    "ShoalError",
    "UnsupportedError",
    "SystemPermissions",
    "TableInfo",
    "TableCompactions",
    "TableOperations",
    "TablePermissions",
    "TableRates",
    "TabletServerStatus",
    "Mutation",
    "SequentialRFile",
    "ZookeeperInstance",
]
