// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/knowledge.proto

package knowledgepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetrievalMode int32

const (
	RetrievalMode_RETRIEVAL_MODE_UNSPECIFIED RetrievalMode = 0
	RetrievalMode_RETRIEVAL_MODE_LEXICAL     RetrievalMode = 1
	RetrievalMode_RETRIEVAL_MODE_VECTOR      RetrievalMode = 2
	RetrievalMode_RETRIEVAL_MODE_TREE        RetrievalMode = 3
	RetrievalMode_RETRIEVAL_MODE_GRAPH       RetrievalMode = 4
)

// Enum value maps for RetrievalMode.
var (
	RetrievalMode_name = map[int32]string{
		0: "RETRIEVAL_MODE_UNSPECIFIED",
		1: "RETRIEVAL_MODE_LEXICAL",
		2: "RETRIEVAL_MODE_VECTOR",
		3: "RETRIEVAL_MODE_TREE",
		4: "RETRIEVAL_MODE_GRAPH",
	}
	RetrievalMode_value = map[string]int32{
		"RETRIEVAL_MODE_UNSPECIFIED": 0,
		"RETRIEVAL_MODE_LEXICAL":     1,
		"RETRIEVAL_MODE_VECTOR":      2,
		"RETRIEVAL_MODE_TREE":        3,
		"RETRIEVAL_MODE_GRAPH":       4,
	}
)

func (x RetrievalMode) Enum() *RetrievalMode {
	p := new(RetrievalMode)
	*p = x
	return p
}

func (x RetrievalMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetrievalMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_knowledge_proto_enumTypes[0].Descriptor()
}

func (RetrievalMode) Type() protoreflect.EnumType {
	return &file_proto_knowledge_proto_enumTypes[0]
}

func (x RetrievalMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetrievalMode.Descriptor instead.
func (RetrievalMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{0}
}

type RetrievalScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentIds   []string               `protobuf:"bytes,1,rep,name=document_ids,json=documentIds,proto3" json:"document_ids,omitempty"`
	NodeIds       []string               `protobuf:"bytes,2,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievalScope) Reset() {
	*x = RetrievalScope{}
	mi := &file_proto_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievalScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievalScope) ProtoMessage() {}

func (x *RetrievalScope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievalScope.ProtoReflect.Descriptor instead.
func (*RetrievalScope) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *RetrievalScope) GetDocumentIds() []string {
	if x != nil {
		return x.DocumentIds
	}
	return nil
}

func (x *RetrievalScope) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

type RetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	TopK          uint32                 `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Modes         []RetrievalMode        `protobuf:"varint,3,rep,packed,name=modes,proto3,enum=shoal.knowledge.v1.RetrievalMode" json:"modes,omitempty"`
	Scope         *RetrievalScope        `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	AsOf          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	Explain       bool                   `protobuf:"varint,6,opt,name=explain,proto3" json:"explain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_proto_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *RetrieveRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RetrieveRequest) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RetrieveRequest) GetModes() []RetrievalMode {
	if x != nil {
		return x.Modes
	}
	return nil
}

func (x *RetrieveRequest) GetScope() *RetrievalScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *RetrieveRequest) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

func (x *RetrieveRequest) GetExplain() bool {
	if x != nil {
		return x.Explain
	}
	return false
}

type SourcePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourcePosition) Reset() {
	*x = SourcePosition{}
	mi := &file_proto_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourcePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourcePosition) ProtoMessage() {}

func (x *SourcePosition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourcePosition.ProtoReflect.Descriptor instead.
func (*SourcePosition) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *SourcePosition) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SourcePosition) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type SourceRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *SourcePosition        `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *SourcePosition        `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceRange) Reset() {
	*x = SourceRange{}
	mi := &file_proto_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRange) ProtoMessage() {}

func (x *SourceRange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRange.ProtoReflect.Descriptor instead.
func (*SourceRange) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *SourceRange) GetStart() *SourcePosition {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *SourceRange) GetEnd() *SourcePosition {
	if x != nil {
		return x.End
	}
	return nil
}

type Citation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	RevisionId    string                 `protobuf:"bytes,2,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	SectionId     string                 `protobuf:"bytes,3,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,4,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Range         *SourceRange           `protobuf:"bytes,5,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Citation) Reset() {
	*x = Citation{}
	mi := &file_proto_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Citation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Citation) ProtoMessage() {}

func (x *Citation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Citation.ProtoReflect.Descriptor instead.
func (*Citation) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *Citation) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Citation) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *Citation) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *Citation) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Citation) GetRange() *SourceRange {
	if x != nil {
		return x.Range
	}
	return nil
}

type GraphNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Labels        []string               `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNode) Reset() {
	*x = GraphNode{}
	mi := &file_proto_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNode) ProtoMessage() {}

func (x *GraphNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNode.ProtoReflect.Descriptor instead.
func (*GraphNode) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{5}
}

func (x *GraphNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphNode) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GraphNode) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *GraphNode) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type GraphEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Weight        float64                `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphEdge) Reset() {
	*x = GraphEdge{}
	mi := &file_proto_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEdge) ProtoMessage() {}

func (x *GraphEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEdge.ProtoReflect.Descriptor instead.
func (*GraphEdge) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *GraphEdge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphEdge) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GraphEdge) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *GraphEdge) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GraphEdge) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *GraphEdge) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type GraphPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*GraphNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*GraphEdge           `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphPath) Reset() {
	*x = GraphPath{}
	mi := &file_proto_knowledge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphPath) ProtoMessage() {}

func (x *GraphPath) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphPath.ProtoReflect.Descriptor instead.
func (*GraphPath) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{7}
}

func (x *GraphPath) GetNodes() []*GraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GraphPath) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type Evidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Citation      *Citation              `protobuf:"bytes,1,opt,name=citation,proto3" json:"citation,omitempty"`
	Quote         string                 `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	Path          *GraphPath             `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_proto_knowledge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{8}
}

func (x *Evidence) GetCitation() *Citation {
	if x != nil {
		return x.Citation
	}
	return nil
}

func (x *Evidence) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *Evidence) GetPath() *GraphPath {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *Evidence) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Explanation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modes         []RetrievalMode        `protobuf:"varint,1,rep,packed,name=modes,proto3,enum=shoal.knowledge.v1.RetrievalMode" json:"modes,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Scores        map[string]float64     `protobuf:"bytes,3,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Explanation) Reset() {
	*x = Explanation{}
	mi := &file_proto_knowledge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Explanation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Explanation) ProtoMessage() {}

func (x *Explanation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Explanation.ProtoReflect.Descriptor instead.
func (*Explanation) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{9}
}

func (x *Explanation) GetModes() []RetrievalMode {
	if x != nil {
		return x.Modes
	}
	return nil
}

func (x *Explanation) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Explanation) GetScores() map[string]float64 {
	if x != nil {
		return x.Scores
	}
	return nil
}

type RetrievalResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Evidence      []*Evidence            `protobuf:"bytes,3,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Explanation   *Explanation           `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievalResult) Reset() {
	*x = RetrievalResult{}
	mi := &file_proto_knowledge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievalResult) ProtoMessage() {}

func (x *RetrievalResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievalResult.ProtoReflect.Descriptor instead.
func (*RetrievalResult) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{10}
}

func (x *RetrievalResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RetrievalResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RetrievalResult) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *RetrievalResult) GetExplanation() *Explanation {
	if x != nil {
		return x.Explanation
	}
	return nil
}

type RetrieveResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Results          []*RetrievalResult     `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	EmbeddingSpaceId string                 `protobuf:"bytes,3,opt,name=embedding_space_id,json=embeddingSpaceId,proto3" json:"embedding_space_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_proto_knowledge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{11}
}

func (x *RetrieveResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RetrieveResponse) GetResults() []*RetrievalResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *RetrieveResponse) GetEmbeddingSpaceId() string {
	if x != nil {
		return x.EmbeddingSpaceId
	}
	return ""
}

var File_proto_knowledge_proto protoreflect.FileDescriptor

const file_proto_knowledge_proto_rawDesc = "" +
	"\n" +
	"\x15proto/knowledge.proto\x12\x12shoal.knowledge.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"N\n" +
	"\x0eRetrievalScope\x12!\n" +
	"\fdocument_ids\x18\x01 \x03(\tR\vdocumentIds\x12\x19\n" +
	"\bnode_ids\x18\x02 \x03(\tR\anodeIds\"\xf8\x01\n" +
	"\x0fRetrieveRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\rR\x04topK\x127\n" +
	"\x05modes\x18\x03 \x03(\x0e2!.shoal.knowledge.v1.RetrievalModeR\x05modes\x128\n" +
	"\x05scope\x18\x04 \x01(\v2\".shoal.knowledge.v1.RetrievalScopeR\x05scope\x12/\n" +
	"\x05as_of\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04asOf\x12\x18\n" +
	"\aexplain\x18\x06 \x01(\bR\aexplain\"<\n" +
	"\x0eSourcePosition\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"}\n" +
	"\vSourceRange\x128\n" +
	"\x05start\x18\x01 \x01(\v2\".shoal.knowledge.v1.SourcePositionR\x05start\x124\n" +
	"\x03end\x18\x02 \x01(\v2\".shoal.knowledge.v1.SourcePositionR\x03end\"\xbb\x01\n" +
	"\bCitation\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1f\n" +
	"\vrevision_id\x18\x02 \x01(\tR\n" +
	"revisionId\x12\x1d\n" +
	"\n" +
	"section_id\x18\x03 \x01(\tR\tsectionId\x12\x17\n" +
	"\aspan_id\x18\x04 \x01(\tR\x06spanId\x125\n" +
	"\x05range\x18\x05 \x01(\v2\x1f.shoal.knowledge.v1.SourceRangeR\x05range\"\xd5\x01\n" +
	"\tGraphNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06labels\x18\x03 \x03(\tR\x06labels\x12M\n" +
	"\n" +
	"properties\x18\x04 \x03(\v2-.shoal.knowledge.v1.GraphNode.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\tGraphEdge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x01R\x06weight\x12M\n" +
	"\n" +
	"properties\x18\x06 \x03(\v2-.shoal.knowledge.v1.GraphEdge.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\tGraphPath\x123\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1d.shoal.knowledge.v1.GraphNodeR\x05nodes\x123\n" +
	"\x05edges\x18\x02 \x03(\v2\x1d.shoal.knowledge.v1.GraphEdgeR\x05edges\"\xa3\x01\n" +
	"\bEvidence\x128\n" +
	"\bcitation\x18\x01 \x01(\v2\x1c.shoal.knowledge.v1.CitationR\bcitation\x12\x14\n" +
	"\x05quote\x18\x02 \x01(\tR\x05quote\x121\n" +
	"\x04path\x18\x03 \x01(\v2\x1d.shoal.knowledge.v1.GraphPathR\x04path\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\"\xe0\x01\n" +
	"\vExplanation\x127\n" +
	"\x05modes\x18\x01 \x03(\x0e2!.shoal.knowledge.v1.RetrievalModeR\x05modes\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12C\n" +
	"\x06scores\x18\x03 \x03(\v2+.shoal.knowledge.v1.Explanation.ScoresEntryR\x06scores\x1a9\n" +
	"\vScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xb4\x01\n" +
	"\x0fRetrievalResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x128\n" +
	"\bevidence\x18\x03 \x03(\v2\x1c.shoal.knowledge.v1.EvidenceR\bevidence\x12A\n" +
	"\vexplanation\x18\x04 \x01(\v2\x1f.shoal.knowledge.v1.ExplanationR\vexplanation\"\x9e\x01\n" +
	"\x10RetrieveResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12=\n" +
	"\aresults\x18\x02 \x03(\v2#.shoal.knowledge.v1.RetrievalResultR\aresults\x12,\n" +
	"\x12embedding_space_id\x18\x03 \x01(\tR\x10embeddingSpaceId*\x99\x01\n" +
	"\rRetrievalMode\x12\x1e\n" +
	"\x1aRETRIEVAL_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RETRIEVAL_MODE_LEXICAL\x10\x01\x12\x19\n" +
	"\x15RETRIEVAL_MODE_VECTOR\x10\x02\x12\x17\n" +
	"\x13RETRIEVAL_MODE_TREE\x10\x03\x12\x18\n" +
	"\x14RETRIEVAL_MODE_GRAPH\x10\x042k\n" +
	"\x12KnowledgeRetrieval\x12U\n" +
	"\bRetrieve\x12#.shoal.knowledge.v1.RetrieveRequest\x1a$.shoal.knowledge.v1.RetrieveResponseB4Z2github.com/phrocker/shoal-oss/internal/knowledgepbb\x06proto3"

var (
	file_proto_knowledge_proto_rawDescOnce sync.Once
	file_proto_knowledge_proto_rawDescData []byte
)

func file_proto_knowledge_proto_rawDescGZIP() []byte {
	file_proto_knowledge_proto_rawDescOnce.Do(func() {
		file_proto_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_knowledge_proto_rawDesc), len(file_proto_knowledge_proto_rawDesc)))
	})
	return file_proto_knowledge_proto_rawDescData
}

var file_proto_knowledge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_knowledge_proto_goTypes = []any{
	(RetrievalMode)(0),            // 0: shoal.knowledge.v1.RetrievalMode
	(*RetrievalScope)(nil),        // 1: shoal.knowledge.v1.RetrievalScope
	(*RetrieveRequest)(nil),       // 2: shoal.knowledge.v1.RetrieveRequest
	(*SourcePosition)(nil),        // 3: shoal.knowledge.v1.SourcePosition
	(*SourceRange)(nil),           // 4: shoal.knowledge.v1.SourceRange
	(*Citation)(nil),              // 5: shoal.knowledge.v1.Citation
	(*GraphNode)(nil),             // 6: shoal.knowledge.v1.GraphNode
	(*GraphEdge)(nil),             // 7: shoal.knowledge.v1.GraphEdge
	(*GraphPath)(nil),             // 8: shoal.knowledge.v1.GraphPath
	(*Evidence)(nil),              // 9: shoal.knowledge.v1.Evidence
	(*Explanation)(nil),           // 10: shoal.knowledge.v1.Explanation
	(*RetrievalResult)(nil),       // 11: shoal.knowledge.v1.RetrievalResult
	(*RetrieveResponse)(nil),      // 12: shoal.knowledge.v1.RetrieveResponse
	nil,                           // 13: shoal.knowledge.v1.GraphNode.PropertiesEntry
	nil,                           // 14: shoal.knowledge.v1.GraphEdge.PropertiesEntry
	nil,                           // 15: shoal.knowledge.v1.Explanation.ScoresEntry
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_proto_knowledge_proto_depIdxs = []int32{
	0,  // 0: shoal.knowledge.v1.RetrieveRequest.modes:type_name -> shoal.knowledge.v1.RetrievalMode
	1,  // 1: shoal.knowledge.v1.RetrieveRequest.scope:type_name -> shoal.knowledge.v1.RetrievalScope
	16, // 2: shoal.knowledge.v1.RetrieveRequest.as_of:type_name -> google.protobuf.Timestamp
	3,  // 3: shoal.knowledge.v1.SourceRange.start:type_name -> shoal.knowledge.v1.SourcePosition
	3,  // 4: shoal.knowledge.v1.SourceRange.end:type_name -> shoal.knowledge.v1.SourcePosition
	4,  // 5: shoal.knowledge.v1.Citation.range:type_name -> shoal.knowledge.v1.SourceRange
	13, // 6: shoal.knowledge.v1.GraphNode.properties:type_name -> shoal.knowledge.v1.GraphNode.PropertiesEntry
	14, // 7: shoal.knowledge.v1.GraphEdge.properties:type_name -> shoal.knowledge.v1.GraphEdge.PropertiesEntry
	6,  // 8: shoal.knowledge.v1.GraphPath.nodes:type_name -> shoal.knowledge.v1.GraphNode
	7,  // 9: shoal.knowledge.v1.GraphPath.edges:type_name -> shoal.knowledge.v1.GraphEdge
	5,  // 10: shoal.knowledge.v1.Evidence.citation:type_name -> shoal.knowledge.v1.Citation
	8,  // 11: shoal.knowledge.v1.Evidence.path:type_name -> shoal.knowledge.v1.GraphPath
	0,  // 12: shoal.knowledge.v1.Explanation.modes:type_name -> shoal.knowledge.v1.RetrievalMode
	15, // 13: shoal.knowledge.v1.Explanation.scores:type_name -> shoal.knowledge.v1.Explanation.ScoresEntry
	9,  // 14: shoal.knowledge.v1.RetrievalResult.evidence:type_name -> shoal.knowledge.v1.Evidence
	10, // 15: shoal.knowledge.v1.RetrievalResult.explanation:type_name -> shoal.knowledge.v1.Explanation
	11, // 16: shoal.knowledge.v1.RetrieveResponse.results:type_name -> shoal.knowledge.v1.RetrievalResult
	2,  // 17: shoal.knowledge.v1.KnowledgeRetrieval.Retrieve:input_type -> shoal.knowledge.v1.RetrieveRequest
	12, // 18: shoal.knowledge.v1.KnowledgeRetrieval.Retrieve:output_type -> shoal.knowledge.v1.RetrieveResponse
	18, // [18:19] is the sub-list for method output_type
	17, // [17:18] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_knowledge_proto_init() }
func file_proto_knowledge_proto_init() {
	if File_proto_knowledge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_knowledge_proto_rawDesc), len(file_proto_knowledge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_knowledge_proto_goTypes,
		DependencyIndexes: file_proto_knowledge_proto_depIdxs,
		EnumInfos:         file_proto_knowledge_proto_enumTypes,
		MessageInfos:      file_proto_knowledge_proto_msgTypes,
	}.Build()
	File_proto_knowledge_proto = out.File
	file_proto_knowledge_proto_goTypes = nil
	file_proto_knowledge_proto_depIdxs = nil
}
