// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/knowledge.proto

package knowledgepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnowledgeRetrieval_Retrieve_FullMethodName = "/shoal.knowledge.v1.KnowledgeRetrieval/Retrieve"
)

// KnowledgeRetrievalClient is the client API for KnowledgeRetrieval service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KnowledgeRetrieval exposes transport-neutral, evidence-addressable retrieval.
type KnowledgeRetrievalClient interface {
	Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error)
}

type knowledgeRetrievalClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeRetrievalClient(cc grpc.ClientConnInterface) KnowledgeRetrievalClient {
	return &knowledgeRetrievalClient{cc}
}

func (c *knowledgeRetrievalClient) Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveResponse)
	err := c.cc.Invoke(ctx, KnowledgeRetrieval_Retrieve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeRetrievalServer is the server API for KnowledgeRetrieval service.
// All implementations must embed UnimplementedKnowledgeRetrievalServer
// for forward compatibility.
//
// KnowledgeRetrieval exposes transport-neutral, evidence-addressable retrieval.
type KnowledgeRetrievalServer interface {
	Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error)
	mustEmbedUnimplementedKnowledgeRetrievalServer()
}

// UnimplementedKnowledgeRetrievalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeRetrievalServer struct{}

func (UnimplementedKnowledgeRetrievalServer) Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Retrieve not implemented")
}
func (UnimplementedKnowledgeRetrievalServer) mustEmbedUnimplementedKnowledgeRetrievalServer() {}
func (UnimplementedKnowledgeRetrievalServer) testEmbeddedByValue()                            {}

// UnsafeKnowledgeRetrievalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeRetrievalServer will
// result in compilation errors.
type UnsafeKnowledgeRetrievalServer interface {
	mustEmbedUnimplementedKnowledgeRetrievalServer()
}

func RegisterKnowledgeRetrievalServer(s grpc.ServiceRegistrar, srv KnowledgeRetrievalServer) {
	// If the following call panics, it indicates UnimplementedKnowledgeRetrievalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowledgeRetrieval_ServiceDesc, srv)
}

func _KnowledgeRetrieval_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeRetrievalServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeRetrieval_Retrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeRetrievalServer).Retrieve(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeRetrieval_ServiceDesc is the grpc.ServiceDesc for KnowledgeRetrieval service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeRetrieval_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shoal.knowledge.v1.KnowledgeRetrieval",
	HandlerType: (*KnowledgeRetrievalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Retrieve",
			Handler:    _KnowledgeRetrieval_Retrieve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/knowledge.proto",
}
