package accumulo

import (
	"bytes"
	"encoding/hex"
	"testing"
	"time"
)

// splitPayloadGolden pins Shoal's TABLE_SPLIT payload encoder to bytes
// produced by Apache Accumulo itself. Each want value was generated by
// running TabletMergeabilityUtil.encode's exact logic — the GSonData record
// serialized by ByteArrayToBase64TypeAdapter.createBase64Gson() with Gson
// 2.12.1, the version Accumulo 4 depends on — at upstream commit
// 317c288568e9c46e7854aafb8bb8c4fda6260b12.
type splitPayloadGolden struct {
	name         string
	rowHex       string
	mergeability splitMergeability
	want         string
}

func splitPayloadGoldens() []splitPayloadGolden {
	return []splitPayloadGolden{
		{"ascii-a", "61", neverMergeable(), `{"split":"YQ==","never":true}`},
		{"ascii-row1", "726f7731", neverMergeable(), `{"split":"cm93MQ==","never":true}`},
		{"empty", "", neverMergeable(), `{"split":"","never":true}`},
		{"nul-only", "00", neverMergeable(), `{"split":"AA==","never":true}`},
		{"binary-nul", "0001ff", neverMergeable(), `{"split":"AAH_","never":true}`},
		{"binary-high", "fffe80", neverMergeable(), `{"split":"__6A","never":true}`},
		{"base64url-chars", "fbffbf", neverMergeable(), `{"split":"-_-_","never":true}`},
		{"utf8-multibyte", "e8a18c", neverMergeable(), `{"split":"6KGM","never":true}`},
		{"json-hostile", "6122622f633c3e26", neverMergeable(), `{"split":"YSJiL2M8PiY=","never":true}`},
		{
			"long-row",
			"30313233343536373839616263646566",
			neverMergeable(),
			`{"split":"MDEyMzQ1Njc4OWFiY2RlZg==","never":true}`,
		},
		{"always", "61", mergeableAfter(0), `{"split":"YQ==","never":false,"delay":0}`},
		{
			"after-1day",
			"61",
			mergeableAfter(24 * time.Hour),
			`{"split":"YQ==","never":false,"delay":86400000000000}`,
		},
		{
			"after-100ms",
			"61",
			mergeableAfter(100 * time.Millisecond),
			`{"split":"YQ==","never":false,"delay":100000000}`,
		},
	}
}

func TestEncodeSplitMergeabilityMatchesAccumuloGoldenBytes(t *testing.T) {
	for _, golden := range splitPayloadGoldens() {
		row, err := hex.DecodeString(golden.rowHex)
		if err != nil {
			t.Fatalf("%s: bad golden row hex: %v", golden.name, err)
		}
		encoded, err := encodeSplitMergeability(row, golden.mergeability)
		if err != nil {
			t.Fatalf("%s: %v", golden.name, err)
		}
		if !bytes.Equal(encoded, []byte(golden.want)) {
			t.Fatalf("%s: payload = %q (%x), want %q (%x)",
				golden.name, encoded, encoded, golden.want, golden.want)
		}
	}
}

func TestEncodeSplitMergeabilityCopiesNothingFromCallerRow(t *testing.T) {
	row := []byte{0x00, 'a', 0xff}
	encoded, err := encodeSplitMergeability(row, neverMergeable())
	if err != nil {
		t.Fatal(err)
	}
	row[0] = 'z'
	again, err := encodeSplitMergeability([]byte{0x00, 'a', 0xff}, neverMergeable())
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(encoded, again) {
		t.Fatalf("payload changed with caller row mutation: %q vs %q", encoded, again)
	}
}

func TestEncodeSplitMergeabilityNeverOmitsDelay(t *testing.T) {
	encoded, err := encodeSplitMergeability([]byte("a"), neverMergeable())
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Contains(encoded, []byte("delay")) {
		t.Fatalf("never payload carried a delay field: %s", encoded)
	}
	withDelay, err := encodeSplitMergeability([]byte("a"), mergeableAfter(0))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(withDelay, []byte(`"delay":0`)) {
		t.Fatalf("always payload dropped its zero delay: %s", withDelay)
	}
}
